# Generated by Django 2.2.5 on 2019-09-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidsipApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computadoras',
            new_name='Computadora',
        ),
    ]
